import { createClient } from "@supabase/supabase-js";
import { createHash } from "crypto";
import InterviewResponse from "./InterviewResponse";
export const dynamic="force-dynamic";
function hash(v:string){return createHash("sha256").update(v).digest("hex");}
function esc(v:unknown){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]??c));}
export default async function InterviewReview({params,searchParams}:{params:{interviewId:string},searchParams:{token?:string}}){
 const token=searchParams?.token||"", id=params.interviewId, url=process.env.NEXT_PUBLIC_SUPABASE_URL,service=process.env.SUPABASE_SERVICE_ROLE_KEY;
 if(!url||!service)return <main className="min-h-screen bg-[#FCFCFA] flex items-center justify-center p-6"><div className="rounded-2xl border border-[#DDE5EA] bg-white p-8">Interview service is not configured.</div></main>;
 const admin=createClient(url,service,{auth:{autoRefreshToken:false,persistSession:false}});
 const {data:invite}=await admin.from("interview_invitations").select("*").eq("interview_id",id).eq("invite_type","Candidate").maybeSingle();
 if(!invite||new Date(invite.expires_at).getTime()<Date.now()||hash(token)!==invite.token_hash)return <main className="min-h-screen bg-[#FCFCFA] flex items-center justify-center p-6"><div className="max-w-md rounded-2xl border border-[#DDE5EA] bg-white p-8 text-center"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-[#167D73]">HRANITI</p><h1 className="mt-3 text-xl font-semibold text-[#173454]">Interview link unavailable</h1><p className="mt-2 text-sm text-[#71859A]">This secure interview link is invalid or has expired.</p></div></main>;
 const {data:interview}=await admin.from("interview_requests").select("*").eq("id",id).single();
 if(!interview)return <main className="p-8">Interview not found.</main>;
 const {data:app}=await admin.from("applications").select("user_id,job_id").eq("id",interview.application_id).single();
 const {data:job}=app?await admin.from("jobs").select("title,company_id").eq("id",app.job_id).single():{data:null};
 const {data:candidate}=app?await admin.from("profiles").select("full_name,email").eq("id",app.user_id).single():{data:null};
 const {data:company}=job?await admin.from("companies").select("name").eq("id",job.company_id).single():{data:null};
 const tz=interview.timezone||"UTC"; const time=interview.confirmed_time||interview.proposed_times?.[0];
 let display=time||"Time to be arranged"; try{if(time)display=new Intl.DateTimeFormat("en-GB",{dateStyle:"full",timeStyle:"short",timeZone:tz}).format(new Date(time));}catch{}
 const locked=["Confirmed","Declined","Completed","Cancelled"].includes(String(interview.status));
 return <main className="min-h-screen bg-[#FCFCFA] py-8 px-4 sm:py-12"><div className="mx-auto max-w-2xl"><div className="overflow-hidden rounded-2xl border border-[#DDE5EA] bg-white shadow-sm"><div className="border-b border-[#E6ECEF] px-6 py-6 sm:px-10"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-[#167D73]">{esc(company?.name||"HRaniti")}</p><h1 className="mt-2 text-2xl font-semibold text-[#173454]">Interview invitation</h1><p className="mt-1 text-sm text-[#71859A]">Hello {esc(candidate?.full_name||"Candidate")}. Please review the proposed interview.</p></div><div className="space-y-4 px-6 py-7 sm:px-10"><div className="rounded-xl border border-[#DDE5EA] bg-[#F8FBFA] p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.1em] text-[#8A99A5]">Role</p><p className="mt-1 text-sm font-medium text-[#173454]">{esc(job?.title||"Interview")}</p><p className="mt-4 text-[10px] font-semibold uppercase tracking-[0.1em] text-[#8A99A5]">Time</p><p className="mt-1 text-sm text-[#526A7D]">{esc(display)}</p><p className="mt-1 text-[11px] text-[#9AA8B3]">{esc(tz)} · {esc(String(interview.duration_minutes||60))} minutes</p>{interview.meeting_link&&<p className="mt-4"><a className="text-sm font-medium text-[#167D73]" href={interview.meeting_link}>Open {esc(interview.meeting_provider||"meeting link")}</a></p>}</div>{interview.notes&&<div className="rounded-xl border border-[#DDE5EA] p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.1em] text-[#8A99A5]">Message</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#526A7D]">{esc(interview.notes)}</p></div>}{locked?<div className="rounded-xl bg-[#F8FBFA] p-5 text-center"><p className="text-sm font-medium text-[#173454]">This interview is {String(interview.status||"updated").toLowerCase()}.</p><p className="mt-1 text-xs text-[#71859A]">No further response is required.</p></div>:<InterviewResponse interviewId={id} token={token}/>}</div></div><p className="mt-5 text-center text-[11px] text-[#9AA8B3]">Secure interview response powered by HRaniti.</p></div></main>;
}
