import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { createHash, randomBytes } from "crypto";

export const runtime = "nodejs";
function esc(v:unknown){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]??c));}
function hash(v:string){return createHash("sha256").update(v).digest("hex");}
function when(v:string,tz:string){try{return new Intl.DateTimeFormat("en-GB",{dateStyle:"full",timeStyle:"short",timeZone:tz}).format(new Date(v));}catch{return new Date(v).toLocaleString("en-GB");}}
async function send(key:string,from:string,payload:Record<string,unknown>,idempotencyKey:string){return fetch("https://api.resend.com/emails",{method:"POST",headers:{"Authorization":`Bearer ${key}`,"Content-Type":"application/json","Idempotency-Key":idempotencyKey},body:JSON.stringify(payload)});}
export async function POST(request:Request){
 try{
  const auth=request.headers.get("authorization"); if(!auth?.startsWith("Bearer "))return NextResponse.json({error:"Authentication required."},{status:401});
  const {interviewId}=await request.json(); if(!interviewId)return NextResponse.json({error:"Interview is required."},{status:400});
  const url=process.env.NEXT_PUBLIC_SUPABASE_URL,anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,service=process.env.SUPABASE_SERVICE_ROLE_KEY,resend=process.env.RESEND_API_KEY,from=process.env.RESEND_FROM_EMAIL,appUrl=process.env.NEXT_PUBLIC_APP_URL;
  if(!url||!anon||!service)return NextResponse.json({error:"Supabase server configuration is incomplete."},{status:500});
  if(!resend||!from||!appUrl)return NextResponse.json({error:"Email is not configured yet. Add RESEND_API_KEY, RESEND_FROM_EMAIL and NEXT_PUBLIC_APP_URL in Vercel."},{status:503});
  const client=createClient(url,anon,{global:{headers:{Authorization:auth}}}); const {data:ud,error:ue}=await client.auth.getUser(); if(ue||!ud.user)return NextResponse.json({error:"Your session is no longer valid."},{status:401});
  const admin=createClient(url,service,{auth:{autoRefreshToken:false,persistSession:false}});
  const {data:member}=await admin.from("company_team_members").select("company_id").eq("user_id",ud.user.id).eq("status","Active").limit(1).maybeSingle(); if(!member?.company_id)return NextResponse.json({error:"You are not an active company member."},{status:403});
  const {data:interview}=await admin.from("interview_requests").select("*").eq("id",interviewId).single(); if(!interview)return NextResponse.json({error:"Interview not found."},{status:404});
  const {data:app}=await admin.from("applications").select("id,user_id,job_id,custom_fields").eq("id",interview.application_id).single(); const {data:job}=app?await admin.from("jobs").select("id,title,company_id").eq("id",app.job_id).eq("company_id",member.company_id).single():{data:null}; const {data:candidate}=app?await admin.from("profiles").select("full_name,email").eq("id",app.user_id).single():{data:null};
  if(!app||!job)return NextResponse.json({error:"Interview candidate/job could not be verified."},{status:403});
  const demo=app.custom_fields?.demo_candidate?app.custom_fields:null;
  const candidateName=String(demo?.demo_name||candidate?.full_name||"Candidate");
  const candidateEmail=String(demo?.demo_email||candidate?.email||"");
  if(!candidateEmail)return NextResponse.json({error:"The candidate has no email address."},{status:400});
  const proposed=interview.confirmed_time||interview.proposed_times?.[0]; if(!proposed)return NextResponse.json({error:"Add an interview time before sending the invitation."},{status:400});
  const {data:company}=await admin.from("companies").select("name").eq("id",member.company_id).single(); const companyName=company?.name||"HRaniti",tz=interview.timezone||"UTC",base=appUrl.replace(/\/$/,""),displayWhen=when(proposed,tz);
  const token=randomBytes(32).toString("hex"),tokenHash=hash(token),expires=new Date(Date.now()+14*86400000).toISOString();
  const {data:old}=await admin.from("interview_invitations").select("id").eq("interview_id",interview.id).eq("invite_type","Candidate").eq("email",candidateEmail).maybeSingle();
  if(old)await admin.from("interview_invitations").update({token_hash:tokenHash,status:"Invited",expires_at:expires,last_sent_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",old.id);
  else await admin.from("interview_invitations").insert({interview_id:interview.id,company_id:member.company_id,email:candidateEmail,name:candidateName,invite_type:"Candidate",token_hash:tokenHash,status:"Invited",expires_at:expires,last_sent_at:new Date().toISOString()});
  const review=`${base}/interview-review/${encodeURIComponent(interview.id)}?token=${token}`;
  const html=`<div style="max-width:620px;margin:32px auto;background:#fff;border:1px solid #e1e8e7;border-radius:18px;padding:36px;font-family:Arial,sans-serif;color:#173454"><div style="font-weight:700;font-size:22px">${esc(companyName)}</div><p style="margin-top:30px">Dear ${esc(candidateName)},</p><p>We would like to invite you to an interview for <strong>${esc(job.title||"the role")}</strong>.</p><div style="margin:24px 0;padding:18px;border-radius:12px;background:#f7faf9;border:1px solid #e2ebe8"><strong>Proposed time</strong><br/>${esc(displayWhen)}<br/><span style="font-size:12px;color:#71859a">${esc(tz)} · ${esc(String(interview.duration_minutes||60))} minutes</span></div>${interview.meeting_link?`<p><strong>Meeting:</strong> <a href="${esc(interview.meeting_link)}">${esc(interview.meeting_provider||"Join online")}</a></p>`:""}<p style="margin:28px 0"><a href="${review}" style="display:inline-block;background:#167d73;color:#fff;text-decoration:none;padding:13px 20px;border-radius:10px;font-weight:600">Review interview invitation</a></p><p style="font-size:12px;color:#71859a">Use the secure link to confirm the time, request another time, or decline.</p><p>Regards,<br/>Hiring Team<br/><strong>${esc(companyName)}</strong></p></div>`;
  const response=await send(resend,from,{from,to:[candidateEmail],subject:`Interview invitation — ${job.title||"your interview"}`,html,tags:[{name:"category",value:"interview_invitation"},{name:"interview_id",value:interview.id}]},`interview-invitation#${interview.id}#${tokenHash.slice(0,16)}`); const result=await response.json().catch(()=>({})); if(!response.ok)return NextResponse.json({error:result?.message||"Email provider rejected the invitation."},{status:502});
  let externalSent=0; for(const person of (Array.isArray(interview.external_interviewers)?interview.external_interviewers:[])){const email=String(person?.email||"").trim();if(!email)continue;const name=String(person?.name||"Interviewer"),extToken=randomBytes(32).toString("hex");await admin.from("interview_invitations").insert({interview_id:interview.id,company_id:member.company_id,email,name,role:person?.role||null,invite_type:"External",token_hash:hash(extToken),status:"Invited",expires_at:expires,last_sent_at:new Date().toISOString()});const feedback=`${base}/interview-feedback/${encodeURIComponent(interview.id)}?token=${extToken}`;const extHtml=`<div style="max-width:620px;margin:32px auto;background:#fff;border:1px solid #e1e8e7;border-radius:18px;padding:36px;font-family:Arial,sans-serif;color:#173454"><div style="font-weight:700;font-size:22px">${esc(companyName)}</div><p style="margin-top:28px">Hello ${esc(name)},</p><p>You have been invited to participate in an interview for <strong>${esc(job.title||"the role")}</strong>.</p><p><strong>Time:</strong> ${esc(displayWhen)}<br/><strong>Duration:</strong> ${esc(String(interview.duration_minutes||60))} minutes</p>${interview.meeting_link?`<p><strong>Meeting:</strong> <a href="${esc(interview.meeting_link)}">${esc(interview.meeting_provider||"Join online")}</a></p>`:""}<p style="margin:28px 0"><a href="${feedback}" style="display:inline-block;background:#167d73;color:#fff;text-decoration:none;padding:13px 20px;border-radius:10px;font-weight:600">Submit interview feedback</a></p></div>`;const er=await send(resend,from,{from,to:[email],subject:`Interview invitation — ${job.title||"candidate interview"}`,html:extHtml},`interview-external#${interview.id}#${email.toLowerCase()}`);if(er.ok)externalSent++;}
  return NextResponse.json({ok:true,emailId:result?.id||null,externalSent});
 }catch(error){console.error("interview invitation failed",error);return NextResponse.json({error:error instanceof Error?error.message:"Unable to send interview invitation."},{status:500});}
}