"use client";
import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function ProviderAccept(){
 const token=useSearchParams().get("token")||"";const router=useRouter();const supabase=createClient();const [name,setName]=useState("");const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function accept(){setError("");if(!token){setError("This invitation link is missing.");return}if(password.length<8||password!==confirm){setError("Use at least 8 characters and make both passwords match.");return}setBusy(true);const r=await fetch("/api/bgv/provider/accept",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,password,fullName:name})});const body=await r.json().catch(()=>({}));if(!r.ok){setError(body.error||"The invitation could not be accepted.");setBusy(false);return}const login=await supabase.auth.signInWithPassword({email:body.email,password});if(login.error){setError("Account created. Please sign in from the provider portal.");router.push("/provider/login");return}router.push("/provider/bgv")}
 return <main className="min-h-screen bg-[#FCFCFA] px-5 py-12"><div className="mx-auto max-w-md"><div className="rounded-2xl border border-[#DDE5EA] bg-white p-7 shadow-sm"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-[#167D73]">BGV PROVIDER PORTAL</p><h1 className="mt-2 text-2xl font-semibold text-[#173454]">Create your provider account</h1><p className="mt-2 text-sm text-[#71859A]">This invitation gives your provider organization access to the assigned BGV case.</p><div className="mt-7 space-y-4"><label className="block text-xs font-medium text-[#526A7D]">Your name<input className="input mt-1.5" value={name} onChange={e=>setName(e.target.value)} placeholder="Alex Morgan"/></label><label className="block text-xs font-medium text-[#526A7D]">Password<input className="input mt-1.5" type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label><label className="block text-xs font-medium text-[#526A7D]">Confirm password<input className="input mt-1.5" type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} /></label>{error&&<p className="text-xs text-[#B34E3E]">{error}</p>}<button onClick={accept} disabled={busy} className="w-full rounded-xl bg-[#167D73] px-4 py-3 text-sm font-medium text-white disabled:opacity-50">{busy?"Creating account…":"Create account"}</button></div></div></div></main>;
}