"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { Check,X } from "lucide-react";
import EmployerShell from "@/components/employer/EmployerShell";
import { createClient } from "@/lib/supabase/client";
import { getOrCreateCompanyId } from "@/lib/employer/getOrCreateCompany";
export default function ApprovalsPage(){
 const supabase=createClient();const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [working,setWorking]=useState("");
 async function load(){setLoading(true);const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const c=await getOrCreateCompanyId(supabase,user);const {data}=await supabase.from("job_approval_requests").select("*,jobs(title,location,status)").eq("company_id",c).order("created_at",{ascending:false});setItems(data??[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function decide(item:any,status:"Approved"|"Changes requested"){setWorking(item.id);const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {error}=await supabase.from("job_approval_requests").update({status,approved_by:status==="Approved"?user.id:null,decided_at:new Date().toISOString()}).eq("id",item.id);if(!error){await supabase.from("jobs").update({status:status==="Approved"?"active":"draft"}).eq("id",item.job_id)}setWorking("");load()}
 return <EmployerShell><div className="min-h-[calc(100vh-72px)] bg-[#FCFCFA]"><div className="mx-auto max-w-[1050px] px-5 py-8 sm:px-8 sm:py-10"><p className="text-[10px] font-semibold tracking-[0.18em] text-[#167D73] uppercase">HIRING</p><h1 className="mt-2 font-display text-3xl text-[#173454]">Approval Center</h1><p className="mt-1 max-w-2xl text-sm text-[#71859A]">Review jobs that need a second pair of eyes before they go live.</p><div className="mt-8 rounded-2xl border border-[#DDE5EA] bg-white">{loading?<div className="p-8 text-sm text-[#71859A]">Loading approvals…</div>:items.filter(i=>i.status==="Pending").length===0?<div className="p-12 text-center text-sm text-[#71859A]">Nothing needs your approval right now.</div>:items.filter(i=>i.status==="Pending").map(i=><div key={i.id} className="flex flex-col gap-4 border-b border-[#EEF2F4] p-6 last:border-b-0 sm:flex-row sm:items-center sm:justify-between"><div><Link href={`/employer/jobs/${i.job_id}`} className="text-sm font-semibold text-[#173454] hover:text-[#167D73]">{i.jobs?.title||"Job"}</Link><p className="mt-1 text-xs text-[#71859A]">{i.jobs?.location||"Location not set"} · Waiting for approval</p></div><div className="flex gap-2"><button disabled={working===i.id} onClick={()=>decide(i,"Changes requested")} className="rounded-xl border border-[#E7C8C1] px-3 py-2 text-xs font-medium text-[#9D4C3F]"><X size={14} className="inline mr-1"/>Request changes</button><button disabled={working===i.id} onClick={()=>decide(i,"Approved")} className="rounded-xl bg-[#167D73] px-3 py-2 text-xs font-medium text-white"><Check size={14} className="inline mr-1"/>Approve & publish</button></div></div>)}</div></div></div></EmployerShell>
}