"use client";
import { useEffect,useState } from "react";
import { Plus,ShieldCheck,UsersRound,X } from "lucide-react";
import EmployerShell from "@/components/employer/EmployerShell";
import { createClient } from "@/lib/supabase/client";
import { getOrCreateCompanyId } from "@/lib/employer/getOrCreateCompany";
const roles=[["Owner","Full workspace control"],["Admin","Company, team and hiring administration"],["Recruiter","Jobs, applicants and hiring workflows"],["Hiring Manager","Assigned roles and candidate decisions"],["Interviewer","Assigned interviews and feedback"],["Viewer","Read-only access to assigned workspace data"]];
export default function TeamPermissionsPage(){
 const supabase=createClient();const [members,setMembers]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [open,setOpen]=useState(false);const [name,setName]=useState("");const [email,setEmail]=useState("");const [role,setRole]=useState("Recruiter");const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 async function load(){setLoading(true);const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return;}const c=await getOrCreateCompanyId(supabase,user);const {data}=await supabase.from("company_team_members").select("*").eq("company_id",c).order("created_at");setMembers(data??[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function addMember(){setError("");if(!name.trim()||!email.trim()){setError("Name and work email are required.");return}setSaving(true);const {data:{user}}=await supabase.auth.getUser();if(!user){setSaving(false);return}const c=await getOrCreateCompanyId(supabase,user);const {error}=await supabase.from("company_team_members").insert({company_id:c,user_id:user.id,full_name:name.trim(),email:email.trim(),role,status:"Invited"});if(error)setError(error.message);else{setOpen(false);setName("");setEmail("");setRole("Recruiter");await load()}setSaving(false)}
 return <EmployerShell><div className="min-h-[calc(100vh-72px)] bg-[#FCFCFA]"><div className="mx-auto max-w-[1080px] px-5 py-8 sm:px-8 sm:py-10">
 <p className="text-[10px] font-semibold tracking-[0.18em] text-[#167D73] uppercase">SETTINGS · WORKSPACE</p><div className="mt-1 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="font-display text-3xl text-[#173454]">Team & Permissions</h1><p className="mt-1 max-w-2xl text-sm text-[#71859A]">Invite the people involved in hiring and give each person the right level of access.</p></div><button onClick={()=>setOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#167D73] px-4 py-2.5 text-sm font-medium text-white hover:bg-[#126E66]"><Plus size={16}/> Add team member</button></div>
 <section className="mt-8 rounded-2xl border border-[#DDE5EA] bg-white"><div className="border-b border-[#EEF2F4] px-6 py-5"><h2 className="text-sm font-semibold text-[#173454]">People</h2><p className="mt-1 text-xs text-[#71859A]">Recruiter and hiring-manager choices in Post a Job come from this list.</p></div>{loading?<div className="px-6 py-10 text-sm text-[#71859A]">Loading team…</div>:members.length===0?<div className="px-6 py-12 text-center"><UsersRound className="mx-auto text-[#9AA8B3]" size={24}/><p className="mt-3 text-sm text-[#526A7D]">No team members yet.</p></div>:<div className="divide-y divide-[#EEF2F4]">{members.map(m=><div key={m.id} className="flex flex-col gap-3 px-6 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#E7F3F1] text-xs font-semibold text-[#167D73]">{(m.full_name||m.email||"?").slice(0,1).toUpperCase()}</div><div><p className="text-sm font-medium text-[#173454]">{m.full_name||"Team member"}</p><p className="text-xs text-[#71859A]">{m.email||"No email"} · {m.status}</p></div></div><span className="inline-flex w-fit items-center gap-1.5 rounded-full bg-[#F4F7F8] px-3 py-1.5 text-[11px] text-[#526A7D]"><ShieldCheck size={13}/>{m.role}</span></div>)}</div>}</section>
 <section className="mt-6 rounded-2xl border border-[#DDE5EA] bg-white p-6"><h2 className="text-sm font-semibold text-[#173454]">Role guide</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{roles.map(([r,d])=><div key={r} className="rounded-xl border border-[#EEF2F4] bg-[#FCFDFD] p-4"><p className="text-sm font-medium text-[#173454]">{r}</p><p className="mt-1 text-xs leading-5 text-[#71859A]">{d}</p></div>)}</div></section>
 {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-[#173454]/20 p-4"><div className="w-full max-w-md rounded-2xl border border-[#DDE5EA] bg-white p-6 shadow-[0_20px_60px_rgba(23,52,84,0.18)]"><div className="flex items-start justify-between"><div><h2 className="text-lg font-semibold text-[#173454]">Add team member</h2><p className="mt-1 text-xs text-[#71859A]">They can be selected when building a job.</p></div><button onClick={()=>setOpen(false)} className="text-[#71859A]"><X size={18}/></button></div><div className="mt-5 space-y-4"><label className="block text-xs font-medium text-[#526A7D]">Full name<input className="input mt-1.5" value={name} onChange={e=>setName(e.target.value)} placeholder="Priya Sharma"/></label><label className="block text-xs font-medium text-[#526A7D]">Work email<input className="input mt-1.5" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="priya@company.com"/></label><label className="block text-xs font-medium text-[#526A7D]">Role<select className="input mt-1.5" value={role} onChange={e=>setRole(e.target.value)}>{roles.map(([r])=><option key={r}>{r}</option>)}</select></label>{error&&<p className="text-xs text-[#B34E3E]">{error}</p>}<button disabled={saving} onClick={addMember} className="w-full rounded-xl bg-[#167D73] px-4 py-3 text-sm font-medium text-white disabled:opacity-50">{saving?"Saving…":"Add team member"}</button></div></div></div>}
 </div></div></EmployerShell>
}