"use client";
import { useState } from "react";
import { ArrowLeft,Plus,Trash2 } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import EmployerShell from "@/components/employer/EmployerShell";
import { createClient } from "@/lib/supabase/client";
import { getOrCreateCompanyId } from "@/lib/employer/getOrCreateCompany";
export default function NewAssessmentPage(){
 const router=useRouter();const supabase=createClient();const [name,setName]=useState("");const [type,setType]=useState("Skills");const [description,setDescription]=useState("");const [duration,setDuration]=useState("30");const [passing,setPassing]=useState("70");const [questions,setQuestions]=useState<string[]>([]);const [draft,setDraft]=useState("");const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 async function save(){if(!name.trim()){setError("Assessment name is required.");return}setSaving(true);const {data:{user}}=await supabase.auth.getUser();if(!user){setError("Please sign in again.");setSaving(false);return}const c=await getOrCreateCompanyId(supabase,user);const {error}=await supabase.from("assessments").insert({company_id:c,name:name.trim(),type,description:description.trim(),config:{durationMinutes:Number(duration),passingScore:Number(passing),questions:questions.map(q=>({type:"short_answer",text:q}))},created_by:user.id});if(error)setError(error.message);else router.push("/employer/settings/hiring");setSaving(false)}
 return <EmployerShell><div className="min-h-[calc(100vh-72px)] bg-[#FCFCFA]"><div className="mx-auto max-w-[900px] px-5 py-8 sm:px-8 sm:py-10"><Link href="/employer/settings/hiring" className="inline-flex items-center gap-2 text-[13px] text-[#71859A]"><ArrowLeft size={15}/> Back to Hiring Configuration</Link><p className="mt-6 text-[10px] font-semibold tracking-[0.18em] text-[#167D73] uppercase">HIRING · ASSESSMENT</p><h1 className="mt-2 font-display text-3xl text-[#173454]">Create an assessment</h1><p className="mt-1 max-w-2xl text-sm text-[#71859A]">Keep it focused. An assessment should add useful evidence, not another hurdle.</p>
 <section className="mt-8 rounded-2xl border border-[#DDE5EA] bg-white p-6 sm:p-8"><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-medium text-[#526A7D]">Name<input className="input mt-1.5" value={name} onChange={e=>setName(e.target.value)} placeholder="SAP ABAP technical assessment"/></label><label className="text-xs font-medium text-[#526A7D]">Type<select className="input mt-1.5" value={type} onChange={e=>setType(e.target.value)}><option>Technical</option><option>Skills</option><option>Aptitude</option><option>Case Study</option><option>Take-home</option><option>Custom</option></select></label></div><label className="mt-4 block text-xs font-medium text-[#526A7D]">Description<textarea className="input mt-1.5 min-h-[100px]" value={description} onChange={e=>setDescription(e.target.value)} placeholder="What is this assessment intended to evaluate?"/></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-xs font-medium text-[#526A7D]">Time limit (minutes)<input className="input mt-1.5" type="number" min="1" value={duration} onChange={e=>setDuration(e.target.value)}/></label><label className="text-xs font-medium text-[#526A7D]">Passing score (%)<input className="input mt-1.5" type="number" min="0" max="100" value={passing} onChange={e=>setPassing(e.target.value)}/></label></div>
 <div className="mt-6 border-t border-[#EEF2F4] pt-6"><div className="flex items-end justify-between"><div><h2 className="text-sm font-semibold text-[#173454]">Questions</h2><p className="mt-1 text-xs text-[#71859A]">Start simple. More question types can be added later.</p></div></div><div className="mt-4 flex gap-2"><input className="input flex-1" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Add a question"/><button onClick={()=>{if(draft.trim()){setQuestions(v=>[...v,draft.trim()]);setDraft("")}}} className="w-11 rounded-xl border border-[#DDE5EA] text-[#167D73]"><Plus size={16} className="mx-auto"/></button></div><div className="mt-3 space-y-2">{questions.map((q,i)=><div key={i} className="flex items-center justify-between rounded-xl bg-[#F5F8F8] px-4 py-3 text-xs text-[#526A7D]"><span>{i+1}. {q}</span><button onClick={()=>setQuestions(v=>v.filter((_,j)=>j!==i))} className="text-[#9AA8B3]"><Trash2 size={14}/></button></div>)}</div></div>{error&&<p className="mt-4 text-sm text-[#B34E3E]">{error}</p>}<div className="mt-8 flex justify-end gap-2"><Link href="/employer/settings/hiring" className="rounded-xl px-4 py-2.5 text-sm text-[#71859A]">Cancel</Link><button disabled={saving} onClick={save} className="rounded-xl bg-[#167D73] px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">{saving?"Saving…":"Save assessment"}</button></div></section></div></div></EmployerShell>
}