"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CalendarDays, CheckCircle2, ClipboardCheck, FileText, History, Mail, MessageSquareText, MoreHorizontal, XCircle } from "lucide-react";
import EmployerShell from "@/components/employer/EmployerShell";
import { createClient } from "@/lib/supabase/client";
import { getOrCreateCompanyId } from "@/lib/employer/getOrCreateCompany";

type App={id:string;user_id:string;job_id:string;status:string|null;applied_at:string;pipeline_stage:string|null;match_score:number|null;skill_score:number|null;experience_score:number|null;location_score:number|null;next_step:string|null;employer_feedback:string|null;expected_timeline:string|null;updated_at:string|null};
type Job={id:string;title:string;location:string|null;employment_type:string|null;description:string|null;career_track:string|null};
type HiringPipeline={id:string;name:string;stages:any;is_default:boolean|null};
type Profile={id:string;full_name:string|null;email:string|null;phone:string|null;linkedin_url:string|null;professional_summary:string|null;current_company:string|null;current_designation:string|null;years_experience:string|null;current_location:string|null;experience:any;education:any;skills:any;certifications:any;notice_period:string|null;availability_status:string|null;work_preference:string[]|null;expected_salary:number|null;salary_currency:string|null;resume_uploaded:boolean|null};
type Tab="Overview"|"Resume"|"Experience"|"Assessments"|"Interviews"|"Feedback"|"Notes"|"Activity";

const aliases:Record<string,string>={applied:"Applied",new:"Applied",screening:"Recruiter Screen","recruiter screen":"Recruiter Screen",assessment:"Assessment",interview:"Technical Interview","technical interview":"Technical Interview","hiring manager review":"Hiring Manager Review",offer:"Offer",hired:"Hired"};
const stage=(v?:string|null)=>v?(aliases[v.toLowerCase().trim()]??v):"Applied";
const date=(v?:string|null)=>v?new Date(v).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"}):"—";
const initials=(v?:string|null)=>(v??"Candidate").split(" ").filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase();
const defaultStages=["Applied","Recruiter Screen","Assessment","Technical Interview","Hiring Manager Review","Offer","Hired"];
function stagesFor(job:Job,pipelines:HiringPipeline[]=[]){try{const x=JSON.parse(job.description??"");const p=x?.process??{};const custom=p?.customPipeline?.stages??p?.customPipelineStages??p?.pipelineStages;if(Array.isArray(custom)&&custom.length)return custom.map((s:any)=>typeof s==="string"?s:s?.name).filter(Boolean).map((s:string)=>stage(s));const saved=pipelines.find(x=>x.name===p.pipeline||x.id===p.pipeline);if(saved?.stages){const s=Array.isArray(saved.stages)?saved.stages:[];if(s.length)return s.map((v:any)=>typeof v==="string"?v:v?.name).filter(Boolean).map((v:string)=>stage(v));}if(p.pipeline==="Leadership")return ["Applied","Recruiter Screen","Leadership Interview","Executive Review","Offer","Hired"];if(p.pipeline==="Technical hiring"){const s=["Applied","Recruiter Screen","Assessment","Technical Interview","Hiring Manager Review","Offer","Hired"];return p.assessment==="None"?s.filter(x=>x!=="Assessment"):s}}catch{}return defaultStages}
function nextStageFor(job:Job,current:string,pipelines:HiringPipeline[]=[]){const stages=stagesFor(job,pipelines);const i=stages.findIndex(s=>s.toLowerCase()===stage(current).toLowerCase());return i>=0&&i<stages.length-1?stages[i+1]:null}

export default function ApplicantDetail({params}:{params:{id:string}}){
 const supabase=createClient();
 const [app,setApp]=useState<App|null>(null),[job,setJob]=useState<Job|null>(null),[profile,setProfile]=useState<Profile|null>(null),[pipelines,setPipelines]=useState<HiringPipeline[]>([]);
 const [assessment,setAssessment]=useState<any[]>([]),[interviews,setInterviews]=useState<any[]>([]),[offer,setOffer]=useState<any|null>(null),[rejection,setRejection]=useState<any|null>(null);
 const [tab,setTab]=useState<Tab>("Overview"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[note,setNote]=useState(""),[showActions,setShowActions]=useState(false);
 const isDemo=params.id==="demo-candidate-1";

 async function load(){
  setLoading(true);
  if(isDemo){
   setApp({id:"demo-candidate-1",user_id:"demo-candidate-1",job_id:"",status:"Active",applied_at:"2026-09-28T09:30:00Z",pipeline_stage:"Applied",match_score:91,skill_score:94,experience_score:92,location_score:88,next_step:"Review profile",employer_feedback:null,expected_timeline:"3-5 days",updated_at:"2026-09-28T09:30:00Z"});
   setProfile({id:"demo-candidate-1",full_name:"Aarav Mehta",email:"aarav.mehta@example.com",phone:"+91 98765 43210",linkedin_url:"https://www.linkedin.com/in/aarav-mehta",professional_summary:"SAP ABAP professional with 8 years of experience across S/4HANA, ABAP development and enterprise integrations.",current_company:"TechNova Solutions",current_designation:"Senior SAP ABAP Consultant",years_experience:"8 years",current_location:"Bengaluru, India",experience:[{company:"TechNova Solutions",role:"Senior SAP ABAP Consultant",duration:"2021–Present"},{company:"Enterprise Systems India",role:"SAP ABAP Consultant",duration:"2018–2021"}],education:[{degree:"B.Tech, Computer Science",institution:"Bengaluru Institute of Technology"}],skills:["SAP ABAP","S/4HANA","CDS Views","OData","BAdIs"],certifications:["SAP Certified Development Professional"],notice_period:"30 days",availability_status:"Available in 30 days",work_preference:["Hybrid"],expected_salary:2800000,salary_currency:"INR",resume_uploaded:true});
   setJob({id:"demo-job",title:"SAP ABAP HANA Developer",location:"Bengaluru, India",employment_type:"Full-time",description:"",career_track:"SAP"});
   setLoading(false);return;
  } const {data:{user}}=await supabase.auth.getUser(); if(!user){setLoading(false);return}
  const company=await getOrCreateCompanyId(supabase,user);
  const {data:a}=await supabase.from("applications").select("id,user_id,job_id,status,applied_at,pipeline_stage,match_score,skill_score,experience_score,location_score,next_step,employer_feedback,expected_timeline,updated_at").eq("id",params.id).single();
  if(!a){setLoading(false);return}
  setApp(a as App);
  const [{data:j},{data:pr}]=await Promise.all([
   supabase.from("jobs").select("id,title,location,employment_type,description,career_track").eq("id",a.job_id).eq("company_id",company).single(),
   supabase.from("hiring_pipelines").select("id,name,stages,is_default").eq("company_id",company).order("created_at")
  ]); setJob(j as Job); setPipelines((pr??[]) as HiringPipeline[]);
  const {data:p}=await supabase.from("profiles").select("id,full_name,email,phone,linkedin_url,professional_summary,current_company,current_designation,years_experience,current_location,experience,education,skills,certifications,notice_period,availability_status,work_preference,expected_salary,salary_currency,resume_uploaded").eq("id",a.user_id).single(); setProfile(p as Profile);
  const [{data:ar},{data:ir},{data:o},{data:r}]=await Promise.all([
   supabase.from("assessment_results").select("*").eq("user_id",a.user_id).order("completed_at",{ascending:false}),
   supabase.from("interview_requests").select("*").eq("application_id",a.id).order("created_at",{ascending:false}),
   supabase.from("offers").select("*").eq("application_id",a.id).order("created_at",{ascending:false}).limit(1),
   supabase.from("rejections").select("*").eq("application_id",a.id).order("created_at",{ascending:false}).limit(1)
  ]);
  setAssessment(ar??[]);setInterviews(ir??[]);setOffer(o?.[0]??null);setRejection(r?.[0]??null);setNote(a.employer_feedback??"");setLoading(false);
 }
 useEffect(()=>{load()},[params.id]); // eslint-disable-line react-hooks/exhaustive-deps

 async function update(patch:Partial<App>){
  if(!app)return;
  if(isDemo){setApp({...app,...patch});return;}setSaving(true);const {error}=await supabase.from("applications").update(patch).eq("id",app.id);if(!error)setApp({...app,...patch});setSaving(false);
 }
 async function saveNote(){await update({employer_feedback:note})}
 async function move(next:string){const x=job?stagesFor(job,pipelines):defaultStages;const i=x.findIndex(s=>s.toLowerCase()===stage(next).toLowerCase());const following=i>=0&&i<x.length-1?x[i+1]:null;await update({pipeline_stage:next,next_step:following?"Move to "+following:"Complete hiring"})}
 async function reject(){const reason=window.prompt("Reason for rejection (optional):","Not selected for this role");if(reason===null)return;await update({status:"rejected",next_step:"Closed"});if(!isDemo){await supabase.from("rejections").insert({application_id:app?.id,reason,note:null});await load()}}
 const currentStage=stage(app?.pipeline_stage); const nextStage=job?nextStageFor(job,currentStage,pipelines):null; const hiringStages=job?stagesFor(job,pipelines):defaultStages;
 const nextAction=nextStage?("Move to "+nextStage):"";
 const doNext=()=>{if(nextStage)move(nextStage)};

 if(loading)return <EmployerShell><div className="px-6 py-16 text-center text-sm text-[#71859A]">Loading candidate…</div></EmployerShell>;
 if(!app||!job||!profile)return <EmployerShell><div className="px-6 py-16 text-center"><p className="text-sm text-[#71859A]">This application could not be found.</p><Link href="/employer/applicants" className="mt-3 inline-flex text-sm text-[#167D73]">Back to Applicants</Link></div></EmployerShell>;

 const tabs:Tab[]=["Overview","Resume","Experience","Assessments","Interviews","Feedback","Notes","Activity"];
 const matchParts=[["Skills alignment",app.skill_score],["Experience alignment",app.experience_score],["Location alignment",app.location_score]];

 return <EmployerShell><div className="min-h-[calc(100vh-72px)] bg-[#FCFCFA]"><div className="mx-auto max-w-[1180px] px-5 py-8 sm:px-8 sm:py-10">
  <Link href={"/employer/applicants?job="+job.id} className="inline-flex items-center gap-2 text-xs text-[#71859A] hover:text-[#173454]"><ArrowLeft size={14}/> Back to {job.title} applicants</Link>
  <div className="mt-5 rounded-2xl border border-[#DDE5EA] bg-white p-6 sm:p-7">
   <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
    <div className="flex gap-4"><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-[#E7F3F1] text-sm font-semibold text-[#167D73]">{initials(profile.full_name)}</span><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#E7F3F1] px-2.5 py-1 text-[10px] font-medium text-[#167D73]">{stage(app.pipeline_stage)}</span><span className="text-xs text-[#9AA8B3]">Applied {date(app.applied_at)}</span></div><h1 className="mt-2 font-display text-2xl text-[#173454]">{profile.full_name??"Candidate"}</h1><p className="mt-1 text-sm text-[#526A7D]">{profile.current_designation??"Applicant"}{profile.current_company?" · "+profile.current_company:""}</p><p className="mt-1 text-xs text-[#71859A]">{profile.current_location??"Location not provided"} · {profile.years_experience??"Experience not provided"}</p></div></div>
    <div className="relative flex flex-wrap items-center gap-2"><select value={currentStage} onChange={e=>move(e.target.value)} disabled={saving} aria-label="Current hiring stage" className="h-10 rounded-xl border border-[#DDE5EA] bg-white px-3 text-xs font-medium text-[#526A7D] outline-none focus:border-[#B9DDD7]">{hiringStages.map(s=><option key={s}>{s}</option>)}</select>{nextStage&&<button onClick={doNext} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-[#167D73] px-4 py-2.5 text-xs font-medium text-white disabled:opacity-60">{nextAction}</button>}{(currentStage==="Recruiter Screen"||currentStage==="Technical Interview")&&<Link href={"/employer/interviews?application="+app.id} className="inline-flex items-center gap-2 rounded-xl border border-[#DDE5EA] bg-white px-4 py-2.5 text-xs font-medium text-[#526A7D]"><CalendarDays size={14}/> Schedule interview</Link>}<button onClick={()=>setShowActions(v=>!v)} className="inline-flex h-10 w-10 items-center justify-center rounded-xl border border-[#DDE5EA] bg-white text-[#71859A]" aria-label="More actions"><MoreHorizontal size={17}/></button>{showActions&&<div className="absolute right-0 top-12 z-20 w-44 rounded-xl border border-[#DDE5EA] bg-white p-1.5 shadow-lg"><button onClick={()=>{setShowActions(false);window.alert("Candidate placed on hold.");update({status:"on_hold",next_step:"On hold"})}} className="block w-full rounded-lg px-3 py-2 text-left text-xs text-[#526A7D] hover:bg-[#F7F9F9]">Put on hold</button><button onClick={()=>{setShowActions(false);reject()}} className="block w-full rounded-lg px-3 py-2 text-left text-xs text-[#B34E3E] hover:bg-[#FFF7F5]">Reject candidate</button></div>}</div>
   </div>
   <div className="mt-6 flex flex-wrap gap-4 text-xs text-[#71859A]"><span className="inline-flex items-center gap-1.5"><Mail size={13}/>{profile.email??"Email unavailable"}</span>{profile.linkedin_url&&<span>{profile.linkedin_url}</span>}<span>Applied for <strong className="font-medium text-[#526A7D]">{job.title}</strong></span></div>
  </div>

  <div className="mt-5 flex gap-1 overflow-x-auto border-b border-[#DDE5EA]">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={"whitespace-nowrap border-b-2 px-3 pb-3 text-xs font-medium "+(tab===t?"border-[#167D73] text-[#167D73]":"border-transparent text-[#71859A] hover:text-[#173454]")}>{t}</button>)}</div>

  {tab==="Overview"&&<div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1fr)_320px]">
   <div className="space-y-5">
    <section className="rounded-2xl border border-[#DDE5EA] bg-white p-6"><h2 className="text-sm font-semibold text-[#173454]">Candidate summary</h2><p className="mt-3 text-sm leading-7 text-[#526A7D]">{profile.professional_summary??"No professional summary has been provided."}</p><div className="mt-5 grid gap-4 sm:grid-cols-3">{[["Availability",profile.availability_status??"—"],["Notice period",profile.notice_period??"—"],["Work preference",(profile.work_preference??[]).join(", ")||"—"]].map(([l,v])=><div key={String(l)}><p className="text-[10px] uppercase tracking-[0.1em] text-[#9AA8B3]">{l}</p><p className="mt-1 text-xs text-[#526A7D]">{v}</p></div>)}</div></section>
    <section className="rounded-2xl border border-[#DDE5EA] bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold text-[#173454]">Match to this job</h2><p className="mt-1 text-xs text-[#71859A]">Use this as evidence, not an automatic hiring decision.</p></div><span className="text-2xl font-semibold text-[#167D73]">{app.match_score!=null?Math.round(Number(app.match_score))+"%":"—"}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{matchParts.map(([l,v])=><div key={String(l)} className="rounded-xl bg-[#F7F9F9] p-3"><p className="text-[10px] text-[#9AA8B3]">{l}</p><p className="mt-1 text-sm font-semibold text-[#173454]">{v!=null?Math.round(Number(v))+"%":"Not scored"}</p></div>)}</div></section>
    <section className="rounded-2xl border border-[#DDE5EA] bg-white p-6"><h2 className="text-sm font-semibold text-[#173454]">Next step</h2><p className="mt-2 text-sm text-[#526A7D]">{nextStage?("Recommended: "+nextAction):"This candidate has reached the end of the hiring stages."}</p><div className="mt-4 flex flex-wrap gap-2">{nextStage&&<button onClick={doNext} disabled={saving} className="rounded-xl bg-[#167D73] px-3 py-2 text-xs font-medium text-white disabled:opacity-60">{nextAction}</button>}{(currentStage==="Recruiter Screen"||currentStage==="Technical Interview")&&<Link href={"/employer/interviews?application="+app.id} className="rounded-xl border border-[#DDE5EA] px-3 py-2 text-xs text-[#526A7D]">Schedule interview</Link>}{currentStage==="Hiring Manager Review"&&<Link href="/employer/offers" className="rounded-xl border border-[#DDE5EA] px-3 py-2 text-xs text-[#526A7D]">Start offer</Link>}{currentStage==="Offer"&&<button onClick={()=>update({status:"hired",pipeline_stage:"Hired",next_step:"Onboard"})} className="rounded-xl border border-[#B9DDD7] bg-[#E7F3F1] px-3 py-2 text-xs text-[#167D73]">Mark hired</button>}<button onClick={reject} className="rounded-xl border border-[#F0D5CF] px-3 py-2 text-xs text-[#B34E3E]">Reject</button></div></section>
   </div>
   <aside className="space-y-5"><section className="rounded-2xl border border-[#DDE5EA] bg-white p-5"><p className="text-[10px] font-semibold tracking-[0.14em] text-[#167D73] uppercase">HIRING CONTEXT</p><p className="mt-3 text-sm font-medium text-[#173454]">{job.title}</p><p className="mt-1 text-xs text-[#71859A]">{job.location??"Location not specified"} · {job.employment_type??"Role"}</p><Link href={"/employer/jobs/"+job.id} className="mt-4 inline-flex text-xs text-[#167D73]">View job →</Link></section><section className="rounded-2xl border border-[#DDE5EA] bg-white p-5"><p className="text-[10px] font-semibold tracking-[0.14em] text-[#167D73] uppercase">PROCESS</p><div className="mt-4 space-y-3"><div><p className="text-[10px] text-[#9AA8B3]">Current stage</p><p className="mt-1 text-xs text-[#526A7D]">{stage(app.pipeline_stage)}</p></div><div><p className="text-[10px] text-[#9AA8B3]">Application status</p><p className="mt-1 text-xs text-[#526A7D]">{statusLabel(app.status)}</p></div><div><p className="text-[10px] text-[#9AA8B3]">Expected timeline</p><p className="mt-1 text-xs text-[#526A7D]">{app.expected_timeline??"—"}</p></div></div></section></aside>
  </div>}

  {tab==="Resume"&&<section className="mt-5 rounded-2xl border border-[#DDE5EA] bg-white p-7"><div className="flex items-center gap-3"><FileText size={19} className="text-[#167D73]"/><div><h2 className="text-sm font-semibold text-[#173454]">Resume</h2><p className="mt-1 text-xs text-[#71859A]">Resume availability and parsed profile information.</p></div></div><div className="mt-6 rounded-xl bg-[#F7F9F9] p-5"><p className="text-sm text-[#526A7D]">{profile.resume_uploaded===false?"No resume is available.":"Resume/profile information is available through the candidate record."}</p><p className="mt-2 text-xs text-[#9AA8B3]">Download and sharing controls should follow the candidate's visibility permissions.</p></div></section>}

  {tab==="Experience"&&<section className="mt-5 rounded-2xl border border-[#DDE5EA] bg-white p-7"><h2 className="text-sm font-semibold text-[#173454]">Experience & education</h2><div className="mt-5 grid gap-5 lg:grid-cols-2"><div><p className="text-[10px] font-semibold tracking-[0.12em] text-[#8A99A5] uppercase">Experience</p><pre className="mt-3 whitespace-pre-wrap font-sans text-xs leading-6 text-[#526A7D]">{JSON.stringify(profile.experience??[],null,2)}</pre></div><div><p className="text-[10px] font-semibold tracking-[0.12em] text-[#8A99A5] uppercase">Education</p><pre className="mt-3 whitespace-pre-wrap font-sans text-xs leading-6 text-[#526A7D]">{JSON.stringify(profile.education??[],null,2)}</pre></div></div></section>}

  {tab==="Assessments"&&<section className="mt-5 rounded-2xl border border-[#DDE5EA] bg-white p-7"><div className="flex items-center gap-3"><ClipboardCheck size={19} className="text-[#167D73]"/><div><h2 className="text-sm font-semibold text-[#173454]">Assessments</h2><p className="mt-1 text-xs text-[#71859A]">Assessment evidence linked to this candidate.</p></div></div>{assessment.length?<div className="mt-5 space-y-3">{assessment.map(x=><div key={x.id} className="rounded-xl border border-[#EEF2F4] p-4"><div className="flex justify-between gap-4"><span className="text-sm font-medium text-[#173454]">{x.assessment_type??"Assessment"}</span><span className="text-sm font-semibold text-[#167D73]">{x.score!=null?x.score+"/100":"—"}</span></div><p className="mt-1 text-xs text-[#71859A]">{x.completed_at?"Completed "+date(x.completed_at):"Not completed"}{x.passed===true?" · Passed":x.passed===false?" · Not passed":""}</p></div>)}</div>:<div className="mt-5 rounded-xl bg-[#F7F9F9] p-5 text-sm text-[#71859A]">No assessment result is recorded yet.</div>}</section>}

  {tab==="Interviews"&&<section className="mt-5 rounded-2xl border border-[#DDE5EA] bg-white p-7"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold text-[#173454]">Interviews</h2><p className="mt-1 text-xs text-[#71859A]">Interview requests and confirmed times for this application.</p></div><Link href={"/employer/interviews?application="+app.id} className="inline-flex items-center gap-2 rounded-xl bg-[#167D73] px-4 py-2.5 text-xs font-medium text-white"><CalendarDays size={14}/> Open interviews</Link></div>{interviews.length?<div className="mt-5 space-y-3">{interviews.map(x=><div key={x.id} className="rounded-xl border border-[#EEF2F4] p-4"><p className="text-sm font-medium text-[#173454]">{x.status??"Interview request"}</p><p className="mt-1 text-xs text-[#71859A]">{x.confirmed_time??(x.proposed_times??[]).join(" · ")??"Time to be arranged"}</p></div>)}</div>:<div className="mt-5 rounded-xl bg-[#F7F9F9] p-5 text-sm text-[#71859A]">No interview is scheduled yet.</div>}</section>}

  {tab==="Feedback"&&<section className="mt-5 rounded-2xl border border-[#DDE5EA] bg-white p-7"><div className="flex items-center gap-3"><MessageSquareText size={19} className="text-[#167D73]"/><div><h2 className="text-sm font-semibold text-[#173454]">Hiring feedback</h2><p className="mt-1 text-xs text-[#71859A]">Internal feedback attached to this application.</p></div></div><textarea value={note} onChange={e=>setNote(e.target.value)} rows={7} className="mt-5 w-full rounded-xl border border-[#DDE5EA] bg-white p-4 text-sm leading-6 text-[#526A7D] outline-none focus:border-[#A9D4CE]" placeholder="Add a concise hiring note or interview summary…"/><button disabled={saving} onClick={saveNote} className="mt-3 rounded-xl bg-[#167D73] px-4 py-2.5 text-xs font-medium text-white disabled:opacity-50">{saving?"Saving…":"Save feedback"}</button></section>}

  {tab==="Notes"&&<section className="mt-5 rounded-2xl border border-[#DDE5EA] bg-white p-7"><h2 className="text-sm font-semibold text-[#173454]">Internal notes</h2><p className="mt-1 text-xs text-[#71859A]">Keep hiring-team context here. Visibility should follow employer permissions.</p><textarea value={note} onChange={e=>setNote(e.target.value)} rows={9} className="mt-5 w-full rounded-xl border border-[#DDE5EA] p-4 text-sm leading-6 text-[#526A7D] outline-none focus:border-[#A9D4CE]" placeholder="Write an internal note…"/><button disabled={saving} onClick={saveNote} className="mt-3 rounded-xl bg-[#167D73] px-4 py-2.5 text-xs font-medium text-white disabled:opacity-50">{saving?"Saving…":"Save note"}</button></section>}

  {tab==="Activity"&&<section className="mt-5 rounded-2xl border border-[#DDE5EA] bg-white p-7"><div className="flex items-center gap-3"><History size={19} className="text-[#167D73]"/><div><h2 className="text-sm font-semibold text-[#173454]">Application activity</h2><p className="mt-1 text-xs text-[#71859A]">Key application events currently available from the hiring record.</p></div></div><div className="mt-6 space-y-4"><div className="flex gap-3"><span className="mt-1 h-2 w-2 rounded-full bg-[#167D73]"/><div><p className="text-xs font-medium text-[#526A7D]">Application received</p><p className="text-[11px] text-[#9AA8B3]">{date(app.applied_at)}</p></div></div><div className="flex gap-3"><span className="mt-1 h-2 w-2 rounded-full bg-[#9AA8B3]"/><div><p className="text-xs font-medium text-[#526A7D]">Current stage: {stage(app.pipeline_stage)}</p><p className="text-[11px] text-[#9AA8B3]">Last updated {date(app.updated_at)}</p></div></div>{rejection&&<div className="flex gap-3"><XCircle size={14} className="text-[#B34E3E]"/><div><p className="text-xs font-medium text-[#526A7D]">Rejected</p><p className="text-[11px] text-[#9AA8B3]">{date(rejection.created_at)} · {rejection.reason??"No reason provided"}</p></div></div>}{offer&&<div className="flex gap-3"><CheckCircle2 size={14} className="text-[#167D73]"/><div><p className="text-xs font-medium text-[#526A7D]">Offer record exists</p><p className="text-[11px] text-[#9AA8B3]">{offer.status??"Status not set"} · {date(offer.created_at)}</p></div></div>}</div></section>}
 </div></div></EmployerShell>
}
function statusLabel(v?:string|null){const x=(v??"").toLowerCase();return x==="rejected"?"Rejected":x==="withdrawn"?"Withdrawn":x==="hired"?"Hired":x==="on_hold"||x==="on hold"?"On hold":"Active"}
