"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Check, ChevronRight, FileCheck2, Filter, Plus, Search, Send, UserRound, X } from "lucide-react";
import EmployerShell from "@/components/employer/EmployerShell";
import { createClient } from "@/lib/supabase/client";
import { getOrCreateCompanyId } from "@/lib/employer/getOrCreateCompany";

type Job={id:string;title:string;location:string|null;employment_type:string|null;work_mode:string|null;salary_min:number|null;salary_max:number|null;salary_currency:string|null;target_start_date:string|null};
type App={id:string;user_id:string;job_id:string;status:string|null;pipeline_stage:string|null};
type Profile={id:string;full_name:string|null;email:string|null;current_designation:string|null;current_company:string|null;expected_salary:number|null;salary_currency:string|null;notice_period:string|null};
type Offer={id:string;application_id:string|null;offer_number:string|null;candidate_name:string|null;candidate_email:string|null;job_title:string|null;status:string|null;created_at:string|null;updated_at:string|null;salary_currency:string|null;pay_frequency:string|null;base_salary:number|null;bonus_target:number|null;bonus_type:string|null;equity:string|null;allowances:string[]|null;benefits:string[]|null;start_date:string|null;work_location:string|null;work_mode:string|null;employment_type:string|null;reporting_to:string|null;probation_period:string|null;notice_period:string|null;offer_expiry_date:string|null;approval_required:boolean|null;approval_note:string|null;approved_at:string|null;sent_at:string|null;responded_at:string|null;candidate_response:string|null;response_note:string|null;candidate_message:string|null;internal_notes:string|null;letter_body:string|null;version:number|null};
type Event={id:string;offer_id:string;event_type:string;created_at:string};

const statuses=["All","Draft","Pending approval","Approved","Sent","Viewed","Changes requested","Accepted","Declined","Expired","Withdrawn"];
const tone:Record<string,string>={Draft:"bg-[#F3F5F6] text-[#667887]","Pending approval":"bg-[#FFF7E8] text-[#9A6A16]",Approved:"bg-[#E7F3F1] text-[#167D73]",Sent:"bg-[#EEF4FF] text-[#3565A8]",Viewed:"bg-[#EEF4FF] text-[#3565A8]","Changes requested":"bg-[#FFF7E8] text-[#9A6A16]",Accepted:"bg-[#E7F3F1] text-[#167D73]",Declined:"bg-[#FFF1EE] text-[#B34E3E]",Expired:"bg-[#F3F5F6] text-[#71859A]",Withdrawn:"bg-[#F3F5F6] text-[#71859A]"};
const fmtDate=(v?:string|null)=>v?new Date(v).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"}):"—";
const money=(n:number|null|undefined,c="INR")=>n==null?"—":new Intl.NumberFormat("en-IN",{style:"currency",currency:c,maximumFractionDigits:0}).format(Number(n));
const initials=(n?:string|null)=>(n??"Candidate").split(" ").filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase();

type Form={applicationId:string;baseSalary:string;currency:string;payFrequency:string;bonus:string;bonusType:string;equity:string;benefits:string;allowances:string;startDate:string;expiryDate:string;workMode:string;workLocation:string;employmentType:string;reportingTo:string;probation:string;notice:string;approvalRequired:boolean;approvalNote:string;candidateMessage:string;letterBody:string;internalNotes:string};
const empty:Form={applicationId:"",baseSalary:"",currency:"INR",payFrequency:"Annual",bonus:"",bonusType:"Target",equity:"",benefits:"",allowances:"",startDate:"",expiryDate:"",workMode:"Hybrid",workLocation:"",employmentType:"Full-time",reportingTo:"",probation:"",notice:"",approvalRequired:true,approvalNote:"",candidateMessage:"",letterBody:"",internalNotes:""};

export default function OffersPage(){
 const supabase=createClient();
 const [jobs,setJobs]=useState<Job[]>([]),[apps,setApps]=useState<App[]>([]),[profiles,setProfiles]=useState<Record<string,Profile>>({}),[offers,setOffers]=useState<Offer[]>([]),[events,setEvents]=useState<Event[]>([]);
 const [companyId,setCompanyId]=useState<string|null>(null),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[statusFilter,setStatusFilter]=useState("All");
 const [selected,setSelected]=useState<Offer|null>(null),[builder,setBuilder]=useState(false),[editing,setEditing]=useState<Offer|null>(null),[form,setForm]=useState<Form>(empty),[saving,setSaving]=useState(false);
 const [response,setResponse]=useState(false),[responseValue,setResponseValue]=useState<"Accepted"|"Changes requested"|"Declined">("Accepted"),[responseNote,setResponseNote]=useState("");

 async function load(){
  setLoading(true);const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}
  const company=await getOrCreateCompanyId(supabase,user);setCompanyId(company);
  const {data:jr}=await supabase.from("jobs").select("id,title,location,employment_type,work_mode,salary_min,salary_max,salary_currency,target_start_date").eq("company_id",company).order("created_at",{ascending:false});
  const j=(jr??[]) as Job[];setJobs(j);const ids=j.map(x=>x.id);if(!ids.length){setApps([]);setOffers([]);setLoading(false);return}
  const {data:ar}=await supabase.from("applications").select("id,user_id,job_id,status,pipeline_stage").in("job_id",ids).order("applied_at",{ascending:false});
  const a=(ar??[]) as App[];setApps(a);
  const u=[...new Set(a.map(x=>x.user_id))];if(u.length){const {data:pr}=await supabase.from("profiles").select("id,full_name,email,current_designation,current_company,expected_salary,salary_currency,notice_period").in("id",u);const m:Record<string,Profile>={};for(const p of (pr??[]) as Profile[])m[p.id]=p;setProfiles(m)}
  const ai=a.map(x=>x.id);if(ai.length){const {data:or}=await supabase.from("offers").select("*").in("application_id",ai).order("created_at",{ascending:false});const os=(or??[]) as Offer[];setOffers(os);if(os.length){const {data:ev}=await supabase.from("offer_events").select("id,offer_id,event_type,created_at").in("offer_id",os.map(x=>x.id)).order("created_at",{ascending:false});setEvents((ev??[]) as Event[])}}else setOffers([]);
  setLoading(false);
 }
 useEffect(()=>{load();const id=new URLSearchParams(window.location.search).get("application");if(id){setForm(x=>({...x,applicationId:id}));setBuilder(true)}},[]); // eslint-disable-line react-hooks/exhaustive-deps

 const jobMap=useMemo(()=>Object.fromEntries(jobs.map(x=>[x.id,x])),[jobs]);
 const appMap=useMemo(()=>Object.fromEntries(apps.map(x=>[x.id,x])),[apps]);
 const filtered=useMemo(()=>offers.filter(o=>{const a=o.application_id?appMap[o.application_id]:null,j=a?jobMap[a.job_id]:null,q=query.toLowerCase().trim();const hay=[o.candidate_name,o.candidate_email,o.job_title,o.offer_number,j?.title].filter(Boolean).join(" ").toLowerCase();return(!q||hay.includes(q))&&(statusFilter==="All"||(o.status??"Draft")===statusFilter)}),[offers,appMap,jobMap,query,statusFilter]);
 const counts=useMemo(()=>Object.fromEntries(statuses.map(s=>[s,s==="All"?offers.length:offers.filter(o=>(o.status??"Draft")===s).length])),[offers]);
 const candidateOptions=useMemo(()=>apps.filter(a=>!["hired","rejected","withdrawn"].includes((a.status??"").toLowerCase())).map(a=>({a,p:profiles[a.user_id],j:jobMap[a.job_id]})).filter(x=>x.p&&x.j),[apps,profiles,jobMap]);

 function set<K extends keyof Form>(k:K,v:Form[K]){setForm(x=>({...x,[k]:v}))}
 function createOffer(id=""){
  const a=appMap[id],p=a?profiles[a.user_id]:null,j=a?jobMap[a.job_id]:null;
  setEditing(null);setForm({...empty,applicationId:id,currency:j?.salary_currency??p?.salary_currency??"INR",baseSalary:p?.expected_salary?String(p.expected_salary):"",startDate:j?.target_start_date??"",workLocation:j?.location??"",workMode:j?.work_mode??"Hybrid",employmentType:j?.employment_type??"Full-time",notice:p?.notice_period??""});setBuilder(true);
 }
 function editOffer(o:Offer){setEditing(o);setForm({applicationId:o.application_id??"",baseSalary:o.base_salary!=null?String(o.base_salary):"",currency:o.salary_currency??"INR",payFrequency:o.pay_frequency??"Annual",bonus:o.bonus_target!=null?String(o.bonus_target):"",bonusType:o.bonus_type??"Target",equity:o.equity??"",benefits:(o.benefits??[]).join(", "),allowances:(o.allowances??[]).join(", "),startDate:o.start_date??"",expiryDate:o.offer_expiry_date??"",workMode:o.work_mode??"Hybrid",workLocation:o.work_location??"",employmentType:o.employment_type??"Full-time",reportingTo:o.reporting_to??"",probation:o.probation_period??"",notice:o.notice_period??"",approvalRequired:o.approval_required!==false,approvalNote:o.approval_note??"",candidateMessage:o.candidate_message??"",letterBody:o.letter_body??"",internalNotes:o.internal_notes??""});setBuilder(true)}
 async function event(id:string,type:string){if(!companyId)return;const {data:{user}}=await supabase.auth.getUser();await supabase.from("offer_events").insert({offer_id:id,company_id:companyId,event_type:type,actor_id:user?.id??null})}
 async function save(e:React.FormEvent){e.preventDefault();const a=appMap[form.applicationId];if(!a||!companyId)return;const p=profiles[a.user_id],j=jobMap[a.job_id];if(!p||!j)return;setSaving(true);const {data:{user}}=await supabase.auth.getUser();const payload:any={application_id:a.id,company_id:companyId,updated_by:user?.id??null,offer_number:editing?.offer_number??\`HR-OFF-\${new Date().getFullYear()}-\${crypto.randomUUID().slice(0,8).toUpperCase()}\`,candidate_name:p.full_name,candidate_email:p.email,job_title:j.title,work_location:form.workLocation,work_mode:form.workMode,employment_type:form.employmentType,salary_currency:form.currency,pay_frequency:form.payFrequency,base_salary:form.baseSalary?Number(form.baseSalary):null,salary:form.baseSalary?money(Number(form.baseSalary),form.currency):null,bonus_target:form.bonus?Number(form.bonus):null,bonus:form.bonus?money(Number(form.bonus),form.currency):null,bonus_type:form.bonusType,equity:form.equity||null,benefits:form.benefits.split(",").map(x=>x.trim()).filter(Boolean),allowances:form.allowances.split(",").map(x=>x.trim()).filter(Boolean),start_date:form.startDate||null,offer_expiry_date:form.expiryDate||null,reporting_to:form.reportingTo||null,probation_period:form.probation||null,notice_period:form.notice||null,approval_required:form.approvalRequired,approval_note:form.approvalNote||null,candidate_message:form.candidateMessage||null,letter_body:form.letterBody||null,internal_notes:form.internalNotes||null,status:editing?.status??"Draft",version:editing?.version??1,updated_at:new Date().toISOString()};if(!editing)payload.created_by=user?.id??null;
  const r=editing?await supabase.from("offers").update(payload).eq("id",editing.id).select("*").single():await supabase.from("offers").insert(payload).select("*").single();if(r.error){alert(r.error.message);setSaving(false);return}const o=r.data as Offer;await event(o.id,editing?"offer_updated":"offer_created");await supabase.from("applications").update({pipeline_stage:"Offer",next_step:o.status==="Approved"?"Send offer":"Complete offer approval"}).eq("id",a.id);setBuilder(false);setEditing(null);await load();setSelected(o);setSaving(false)}
 async function transition(o:Offer,next:string){const now=new Date().toISOString();const patch:any={status:next,updated_at:now};if(next==="Approved"){patch.approved_at=now;patch.approved_by=(await supabase.auth.getUser()).data.user?.id??null}if(next==="Sent")patch.sent_at=now;if(next==="Viewed")patch.viewed_at=now;if(next==="Expired")patch.expired_at=now;if(next==="Withdrawn")patch.withdrawn_at=now;const r=await supabase.from("offers").update(patch).eq("id",o.id);if(r.error){alert(r.error.message);return}const step=next==="Pending approval"?"Await offer approval":next==="Approved"?"Send offer":["Sent","Viewed"].includes(next)?"Awaiting offer response":next==="Changes requested"?"Review requested changes":next==="Accepted"?"Complete pre-employment checks":next==="Declined"?"Review declined offer":next==="Expired"?"Review expired offer":"Offer withdrawn";if(o.application_id)await supabase.from("applications").update({pipeline_stage:"Offer",next_step:step}).eq("id",o.application_id);await event(o.id,next.toLowerCase().replaceAll(" ","_"));await load();setSelected({...o,...patch})}
 async function recordResponse(){if(!selected)return;const now=new Date().toISOString();const r=await supabase.from("offers").update({status:responseValue,candidate_response:responseValue,response_note:responseNote||null,responded_at:now,updated_at:now}).eq("id",selected.id);if(r.error){alert(r.error.message);return}if(selected.application_id)await supabase.from("applications").update({pipeline_stage:"Offer",next_step:responseValue==="Accepted"?"Complete pre-employment checks":responseValue==="Changes requested"?"Review requested changes":"Review declined offer"}).eq("id",selected.application_id);await event(selected.id,"candidate_"+responseValue.toLowerCase().replaceAll(" ","_"));setResponse(false);setResponseNote("");await load();setSelected({...selected,status:responseValue,candidate_response:responseValue,response_note:responseNote||null})}
 async function hired(o:Offer){if(!o.application_id)return;const r=await supabase.from("applications").update({status:"hired",pipeline_stage:"Hired",next_step:"Start onboarding"}).eq("id",o.application_id);if(r.error){alert(r.error.message);return}await event(o.id,"candidate_hired");await load()}
 const selectedApp=selected?.application_id?appMap[selected.application_id]:null,selectedProfile=selectedApp?profiles[selectedApp.user_id]:null,selectedJob=selectedApp?jobMap[selectedApp.job_id]:null;
 return <EmployerShell jobCount={jobs.length}><div className="min-h-[calc(100vh-72px)] bg-[#FCFCFA]"><div className="mx-auto max-w-[1280px] px-5 py-8 sm:px-8 sm:py-10">
  <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-[#167D73]">HIRING</p><h1 className="mt-2 font-display text-3xl text-[#173454]">Offers</h1><p className="mt-2 text-sm text-[#71859A]">Create, approve, send and track offers from one connected workspace.</p></div><button onClick={()=>createOffer()} className="inline-flex items-center gap-2 rounded-xl bg-[#167D73] px-4 py-2.5 text-xs font-medium text-white"><Plus size={15}/> Create offer</button></div>
  <div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">{[["Draft","Draft"],["Pending","Pending approval"],["Approved","Approved"],["Sent","Sent"],["Changes","Changes requested"],["Accepted","Accepted"],["Declined","Declined"],["Expired","Expired"]].map(([l,s])=><button key={l} onClick={()=>setStatusFilter(s)} className="rounded-2xl border border-[#DDE5EA] bg-white p-4 text-left"><p className="text-[10px] uppercase tracking-[.08em] text-[#9AA8B3]">{l}</p><p className="mt-1 text-xl font-semibold text-[#173454]">{counts[s]??0}</p></button>)}</div>
  <div className="mt-6 rounded-2xl border border-[#DDE5EA] bg-white p-3"><div className="flex flex-col gap-2 lg:flex-row"><div className="flex h-10 flex-1 items-center gap-2 rounded-xl bg-[#F7F9F9] px-3"><Search size={15} className="text-[#8A99A5]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search candidate, job or offer number…" className="w-full bg-transparent text-xs outline-none"/></div><label className="flex h-10 items-center rounded-xl border border-[#DDE5EA] px-3"><Filter size={13} className="mr-2 text-[#8A99A5]"/><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="bg-transparent text-xs text-[#526A7D] outline-none">{statuses.map(s=><option key={s}>{s}</option>)}</select></label></div></div>
  <section className="mt-5 overflow-hidden rounded-2xl border border-[#DDE5EA] bg-white"><div className="hidden grid-cols-[minmax(220px,1.35fr)_minmax(180px,1fr)_130px_130px_120px_30px] gap-4 border-b border-[#EEF2F4] px-5 py-3 text-[10px] font-semibold uppercase tracking-[.12em] text-[#8A99A5] md:grid"><span>Candidate</span><span>Role</span><span>Offer</span><span>Compensation</span><span>Status</span><span/></div>{loading?<div className="px-5 py-16 text-center text-sm text-[#71859A]">Loading offers…</div>:!filtered.length?<div className="px-5 py-16 text-center"><FileCheck2 size={22} className="mx-auto text-[#9AA8B3]"/><p className="mt-4 text-sm font-medium text-[#173454]">No offers yet</p><p className="mt-1 text-xs text-[#71859A]">Create an offer from an applicant when the hiring team is ready.</p></div>:filtered.map(o=>{const a=o.application_id?appMap[o.application_id]:null,j=a?jobMap[a.job_id]:null;return <button key={o.id} onClick={()=>setSelected(o)} className="grid w-full grid-cols-1 gap-3 border-b border-[#EEF2F4] px-5 py-4 text-left hover:bg-[#FCFDFD] md:grid-cols-[minmax(220px,1.35fr)_minmax(180px,1fr)_130px_130px_120px_30px] md:items-center md:gap-4"><span className="flex items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#E7F3F1] text-[11px] font-semibold text-[#167D73]">{initials(o.candidate_name)}</span><span><span className="block text-sm font-medium text-[#173454]">{o.candidate_name??"Candidate"}</span><span className="block text-[11px] text-[#71859A]">{o.candidate_email??"Email unavailable"}</span></span></span><span><span className="block truncate text-xs font-medium text-[#526A7D]">{o.job_title??j?.title??"Role"}</span><span className="text-[11px] text-[#9AA8B3]">{j?.location??o.work_location??"—"}</span></span><span className="text-xs text-[#526A7D]">{o.offer_number??"—"}</span><span className="text-xs font-medium text-[#173454]">{o.base_salary!=null?money(o.base_salary,o.salary_currency??"INR"):"—"}<span className="block text-[10px] font-normal text-[#9AA8B3]">{o.pay_frequency??"Annual"}</span></span><span className={"inline-flex w-fit rounded-full px-2.5 py-1 text-[10px] font-medium "+(tone[o.status??"Draft"]??tone.Draft)}>{o.status??"Draft"}</span><ChevronRight size={15} className="text-[#9AA8B3]"/></button>})}</section>
 </div></div>

 {selected&&<div className="fixed inset-0 z-50 bg-[#173454]/20 p-4 sm:p-8" onClick={()=>setSelected(null)}><div className="ml-auto h-full w-full max-w-[620px] overflow-y-auto rounded-2xl border border-[#DDE5EA] bg-white shadow-2xl" onClick={e=>e.stopPropagation()}>
  <div className="sticky top-0 z-10 border-b border-[#EEF2F4] bg-white p-6"><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-[#167D73]">OFFER</p><h2 className="mt-2 text-xl font-semibold text-[#173454]">{selected.candidate_name??"Candidate"}</h2><p className="mt-1 text-xs text-[#71859A]">{selected.job_title} · {selected.offer_number}</p></div><button onClick={()=>setSelected(null)}><X size={18} className="text-[#8A99A5]"/></button></div><div className="mt-4"><span className={"rounded-full px-2.5 py-1 text-[10px] font-medium "+(tone[selected.status??"Draft"]??tone.Draft)}>{selected.status??"Draft"}</span></div></div>
  <div className="space-y-5 p-6">
   <section className="rounded-2xl border border-[#DDE5EA] p-5"><div className="flex items-center gap-3"><UserRound size={17} className="text-[#167D73]"/><div><h3 className="text-sm font-semibold text-[#173454]">Candidate & role</h3><p className="text-xs text-[#71859A]">{selectedProfile?.current_designation??"Applicant"} · {selectedJob?.title??selected.job_title}</p></div></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><div><p className="text-[10px] text-[#9AA8B3]">Email</p><p className="mt-1 text-xs text-[#526A7D]">{selected.candidate_email??"—"}</p></div><div><p className="text-[10px] text-[#9AA8B3]">Start date</p><p className="mt-1 text-xs text-[#526A7D]">{fmtDate(selected.start_date)}</p></div></div>{selected.application_id&&<div className="mt-4 flex flex-wrap gap-2"><Link href={"/employer/applicants/"+selected.application_id} className="rounded-xl border border-[#DDE5EA] px-3 py-2 text-xs text-[#526A7D]">Open applicant</Link><Link href={"/employer/interviews?application="+selected.application_id} className="rounded-xl border border-[#DDE5EA] px-3 py-2 text-xs text-[#526A7D]">Open interviews</Link></div>}</section>
   <section className="rounded-2xl border border-[#DDE5EA] p-5"><h3 className="text-sm font-semibold text-[#173454]">Compensation & terms</h3><div className="mt-4 grid gap-4 sm:grid-cols-2">{[["Base salary",selected.base_salary!=null?money(selected.base_salary,selected.salary_currency??"INR"):"—"],["Bonus",selected.bonus_target!=null?money(selected.bonus_target,selected.salary_currency??"INR"):"—"],["Equity",selected.equity??"—"],["Benefits",(selected.benefits??[]).join(", ")||"—"],["Work mode",selected.work_mode??"—"],["Employment",selected.employment_type??"—"],["Reporting to",selected.reporting_to??"—"],["Offer expiry",fmtDate(selected.offer_expiry_date)]].map(([l,v])=><div key={l}><p className="text-[10px] text-[#9AA8B3]">{l}</p><p className="mt-1 text-xs text-[#526A7D]">{v}</p></div>)}</div></section>
   {(selected.candidate_message||selected.letter_body)&&<section className="rounded-2xl border border-[#DDE5EA] p-5"><h3 className="text-sm font-semibold text-[#173454]">Offer communication</h3>{selected.candidate_message&&<p className="mt-3 whitespace-pre-wrap text-xs leading-6 text-[#526A7D]">{selected.candidate_message}</p>}{selected.letter_body&&<div className="mt-4 whitespace-pre-wrap rounded-xl bg-[#F7F9F9] p-4 text-xs leading-6 text-[#526A7D]">{selected.letter_body}</div>}</section>}
   <section className="rounded-2xl border border-[#DDE5EA] p-5"><h3 className="text-sm font-semibold text-[#173454]">Workflow</h3><div className="mt-4 space-y-3">{["Draft","Pending approval","Approved","Sent","Accepted"].map(s=><div key={s} className="flex items-center gap-3"><span className={"flex h-6 w-6 items-center justify-center rounded-full "+(selected.status===s?"bg-[#167D73] text-white":"bg-[#F3F5F6] text-[#9AA8B3]")}>{selected.status===s?<Check size={13}/>:<span className="h-1.5 w-1.5 rounded-full bg-current"/>}</span><span className={"text-xs "+(selected.status===s?"font-medium text-[#173454]":"text-[#9AA8B3]")}>{s}</span></div>)}</div></section>
   <section className="rounded-2xl border border-[#DDE5EA] p-5"><h3 className="text-sm font-semibold text-[#173454]">Activity</h3><div className="mt-4 space-y-3">{events.filter(e=>e.offer_id===selected.id).map(e=><div key={e.id} className="flex gap-3"><span className="mt-1 h-2 w-2 rounded-full bg-[#167D73]"/><div><p className="text-xs text-[#526A7D]">{e.event_type.replaceAll("_"," ")}</p><p className="text-[10px] text-[#9AA8B3]">{fmtDate(e.created_at)}</p></div></div>)}</div></section>
   <div className="flex flex-wrap gap-2">{(selected.status==="Draft"||selected.status==="Changes requested")&&<button onClick={()=>editOffer(selected)} className="rounded-xl border border-[#DDE5EA] px-3 py-2.5 text-xs text-[#526A7D]">Edit</button>}{selected.status==="Draft"&&selected.approval_required!==false&&<button onClick={()=>transition(selected,"Pending approval")} className="rounded-xl bg-[#173454] px-3 py-2.5 text-xs text-white">Submit for approval</button>}{selected.status==="Draft"&&selected.approval_required===false&&<button onClick={()=>transition(selected,"Approved")} className="rounded-xl bg-[#173454] px-3 py-2.5 text-xs text-white">Approve & continue</button>}{selected.status==="Pending approval"&&<button onClick={()=>transition(selected,"Approved")} className="rounded-xl bg-[#167D73] px-3 py-2.5 text-xs text-white">Approve offer</button>}{selected.status==="Approved"&&<button onClick={()=>transition(selected,"Sent")} className="inline-flex items-center gap-2 rounded-xl bg-[#167D73] px-3 py-2.5 text-xs text-white"><Send size={13}/> Mark sent</button>}{(selected.status==="Sent"||selected.status==="Viewed")&&<button onClick={()=>setResponse(true)} className="rounded-xl border border-[#B9DDD7] bg-[#E7F3F1] px-3 py-2.5 text-xs text-[#167D73]">Record candidate response</button>}{selected.status==="Accepted"&&<button onClick={()=>hired(selected)} className="rounded-xl bg-[#167D73] px-3 py-2.5 text-xs text-white">Mark hired</button>}{!["Accepted","Declined","Withdrawn","Expired"].includes(selected.status??"")&&<button onClick={()=>transition(selected,"Withdrawn")} className="rounded-xl border border-[#F0D5CF] px-3 py-2.5 text-xs text-[#B34E3E]">Withdraw</button>}</div>
  </div>
 </div></div>}

 {builder&&<div className="fixed inset-0 z-[60] overflow-y-auto bg-[#173454]/20 p-4 sm:p-8" onClick={()=>setBuilder(false)}><form onSubmit={save} onClick={e=>e.stopPropagation()} className="mx-auto max-w-4xl rounded-2xl border border-[#DDE5EA] bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-[#EEF2F4] p-6"><div><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-[#167D73]">OFFER BUILDER</p><h2 className="mt-2 text-xl font-semibold text-[#173454]">{editing?"Edit offer":"Create offer"}</h2></div><button type="button" onClick={()=>setBuilder(false)}><X size={18}/></button></div><div className="space-y-6 p-6">
  <section><h3 className="text-sm font-semibold text-[#173454]">Candidate & role</h3><select required disabled={!!editing} value={form.applicationId} onChange={e=>createOffer(e.target.value)} className="mt-3 h-11 w-full rounded-xl border border-[#DDE5EA] bg-white px-3 text-xs"><option value="">Select candidate application…</option>{candidateOptions.map(x=><option key={x.a.id} value={x.a.id}>{x.p?.full_name??x.p?.email} · {x.j?.title}</option>)}</select></section>
  <section><h3 className="text-sm font-semibold text-[#173454]">Compensation</h3><div className="mt-4 grid gap-4 sm:grid-cols-4"><label>Base salary<input type="number" value={form.baseSalary} onChange={e=>set("baseSalary",e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border border-[#DDE5EA] px-3 text-xs"/></label><label>Currency<select value={form.currency} onChange={e=>set("currency",e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border border-[#DDE5EA] px-3 text-xs"><option>INR</option><option>USD</option><option>EUR</option><option>GBP</option><option>AED</option><option>SGD</option><option>SAR</option></select></label><label>Pay frequency<select value={form.payFrequency} onChange={e=>set("payFrequency",e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border border-[#DDE5EA] px-3 text-xs"><option>Annual</option><option>Monthly</option><option>Hourly</option></select></label><label>Target bonus<input type="number" value={form.bonus} onChange={e=>set("bonus",e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border border-[#DDE5EA] px-3 text-xs"/></label></div><div className="mt-4 grid gap-4 sm:grid-cols-3"><label>Bonus type<select value={form.bonusType} onChange={e=>set("bonusType",e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border border-[#DDE5EA] px-3 text-xs"><option>Target</option><option>Sign-on</option><option>Performance</option><option>Discretionary</option></select></label><label>Equity<input value={form.equity} onChange={e=>set("equity",e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border border-[#DDE5EA] px-3 text-xs"/></label><label>Benefits<input value={form.benefits} onChange={e=>set("benefits",e.target.value)} placeholder="Health, PF, leave…" className="mt-1.5 h-11 w-full rounded-xl border border-[#DDE5EA] px-3 text-xs"/></label></div><label className="mt-4 block">Allowances<input value={form.allowances} onChange={e=>set("allowances",e.target.value)} placeholder="Relocation, transport…" className="mt-1.5 h-11 w-full rounded-xl border border-[#DDE5EA] px-3 text-xs"/></label></section>
  <section><h3 className="text-sm font-semibold text-[#173454]">Employment terms</h3><div className="mt-4 grid gap-4 sm:grid-cols-3"><label>Start date<input type="date" value={form.startDate} onChange={e=>set("startDate",e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border border-[#DDE5EA] px-3 text-xs"/></label><label>Offer expiry<input type="date" value={form.expiryDate} onChange={e=>set("expiryDate",e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border border-[#DDE5EA] px-3 text-xs"/></label><label>Employment<select value={form.employmentType} onChange={e=>set("employmentType",e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border border-[#DDE5EA] px-3 text-xs"><option>Full-time</option><option>Part-time</option><option>Contract</option><option>Freelance</option></select></label><label>Work mode<select value={form.workMode} onChange={e=>set("workMode",e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border border-[#DDE5EA] px-3 text-xs"><option>On-site</option><option>Hybrid</option><option>Remote</option></select></label><label>Work location<input value={form.workLocation} onChange={e=>set("workLocation",e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border border-[#DDE5EA] px-3 text-xs"/></label><label>Reporting to<input value={form.reportingTo} onChange={e=>set("reportingTo",e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border border-[#DDE5EA] px-3 text-xs"/></label><label>Probation<input value={form.probation} onChange={e=>set("probation",e.target.value)} placeholder="3 months" className="mt-1.5 h-11 w-full rounded-xl border border-[#DDE5EA] px-3 text-xs"/></label><label>Notice period<input value={form.notice} onChange={e=>set("notice",e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border border-[#DDE5EA] px-3 text-xs"/></label></div></section>
  <section><h3 className="text-sm font-semibold text-[#173454]">Approval & communication</h3><label className="mt-4 flex gap-3 rounded-xl bg-[#F7F9F9] p-4"><input type="checkbox" checked={form.approvalRequired} onChange={e=>set("approvalRequired",e.target.checked)} className="mt-1"/><span className="text-xs"><strong className="text-[#173454]">Require approval before sending</strong><span className="mt-1 block text-[#71859A]">Offer approval should be connected to the hiring team's approval rules.</span></span></label><label className="mt-4 block">Approval note<textarea value={form.approvalNote} onChange={e=>set("approvalNote",e.target.value)} rows={2} className="mt-1.5 w-full rounded-xl border border-[#DDE5EA] p-3 text-xs"/></label><label className="mt-4 block">Candidate message<textarea value={form.candidateMessage} onChange={e=>set("candidateMessage",e.target.value)} rows={3} className="mt-1.5 w-full rounded-xl border border-[#DDE5EA] p-3 text-xs"/></label><label className="mt-4 block">Offer letter content<textarea value={form.letterBody} onChange={e=>set("letterBody",e.target.value)} rows={7} placeholder="Offer letter content…" className="mt-1.5 w-full rounded-xl border border-[#DDE5EA] p-3 text-xs leading-5"/></label><label className="mt-4 block">Internal notes<textarea value={form.internalNotes} onChange={e=>set("internalNotes",e.target.value)} rows={3} className="mt-1.5 w-full rounded-xl border border-[#DDE5EA] p-3 text-xs"/></label></section>
 </div><div className="flex justify-between border-t border-[#EEF2F4] p-6"><button type="button" onClick={()=>setBuilder(false)} className="rounded-xl border border-[#DDE5EA] px-4 py-2.5 text-xs">Cancel</button><button disabled={saving||!form.applicationId} className="rounded-xl bg-[#167D73] px-5 py-2.5 text-xs font-medium text-white disabled:opacity-50">{saving?"Saving…":editing?"Save changes":"Create draft offer"}</button></div></form></div>}

 {response&&selected&&<div className="fixed inset-0 z-[70] flex items-center justify-center bg-[#173454]/20 p-5" onClick={()=>setResponse(false)}><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-[#167D73]">CANDIDATE RESPONSE</p><h2 className="mt-2 text-lg font-semibold text-[#173454]">Record response</h2></div><button onClick={()=>setResponse(false)}><X size={18}/></button></div><div className="mt-5 space-y-2">{(["Accepted","Changes requested","Declined"] as const).map(x=><button key={x} onClick={()=>setResponseValue(x)} className={"w-full rounded-xl border p-3 text-left text-xs "+(responseValue===x?"border-[#A9D4CE] bg-[#E7F3F1] text-[#167D73]":"border-[#DDE5EA] text-[#526A7D]")}>{x}</button>)}</div><textarea value={responseNote} onChange={e=>setResponseNote(e.target.value)} rows={4} className="mt-4 w-full rounded-xl border border-[#DDE5EA] p-3 text-xs" placeholder="Optional response note…"/><button onClick={recordResponse} className="mt-4 w-full rounded-xl bg-[#167D73] py-3 text-xs font-medium text-white">Save response</button></div></div>}
 </EmployerShell>
}