"use client";
import { useEffect,useState } from "react";
import { Plus,Trash2 } from "lucide-react";
import Link from "next/link";
import EmployerShell from "@/components/employer/EmployerShell";
import { createClient } from "@/lib/supabase/client";
import { getOrCreateCompanyId } from "@/lib/employer/getOrCreateCompany";
const base=[["Applied","Application"],["Recruiter screen","Screening"],["Assessment","Assessment"],["Interview","Interview"],["Hiring manager","Hiring Manager Review"],["Offer","Offer"],["Hired","Hired"]];
export default function HiringConfigurationPage(){
 const supabase=createClient();const [pipelines,setPipelines]=useState<any[]>([]);const [assessments,setAssessments]=useState<any[]>([]);const [open,setOpen]=useState(false);const [name,setName]=useState("");const [stages,setStages]=useState(base.map(([name,type])=>({name,type})));const [saving,setSaving]=useState(false);
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const c=await getOrCreateCompanyId(supabase,user);const [p,a]=await Promise.all([supabase.from("hiring_pipelines").select("*").eq("company_id",c).order("created_at"),supabase.from("assessments").select("*").eq("company_id",c).order("created_at")]);setPipelines(p.data??[]);setAssessments(a.data??[])}
 useEffect(()=>{load()},[]);
 async function save(){if(!name.trim()||stages.length<2)return;setSaving(true);const {data:{user}}=await supabase.auth.getUser();if(!user){setSaving(false);return}const c=await getOrCreateCompanyId(supabase,user);await supabase.from("hiring_pipelines").insert({company_id:c,name:name.trim(),stages,created_by:user.id});setName("");setStages(base.map(([name,type])=>({name,type})));setOpen(false);setSaving(false);load()}
 return <EmployerShell><div className="min-h-[calc(100vh-72px)] bg-[#FCFCFA]"><div className="mx-auto max-w-[1080px] px-5 py-8 sm:px-8 sm:py-10"><p className="text-[10px] font-semibold tracking-[0.18em] text-[#167D73] uppercase">SETTINGS · HIRING</p><h1 className="mt-2 font-display text-3xl text-[#173454]">Hiring configuration</h1><p className="mt-1 max-w-2xl text-sm text-[#71859A]">Set reusable hiring workflows once. Keep individual job setup light.</p><div className="mt-8 grid gap-6 lg:grid-cols-2">
 <section className="rounded-2xl border border-[#DDE5EA] bg-white p-6"><div className="flex items-start justify-between"><div><h2 className="text-base font-semibold text-[#173454]">Hiring pipelines</h2><p className="mt-1 text-xs text-[#71859A]">A pipeline is simply the sequence a candidate moves through.</p></div><button onClick={()=>setOpen(true)} className="rounded-xl border border-[#B9DDD7] px-3 py-2 text-xs font-medium text-[#167D73]"><Plus size={14} className="inline mr-1"/>Create</button></div><div className="mt-5 space-y-3">{pipelines.length===0?<div className="rounded-xl bg-[#F5F8F8] p-4 text-xs leading-5 text-[#71859A]">No custom pipelines yet. Standard remains available in every job.</div>:pipelines.map(p=><div key={p.id} className="rounded-xl border border-[#EEF2F4] p-4"><p className="text-sm font-medium text-[#173454]">{p.name}</p><p className="mt-1 text-xs text-[#71859A]">{(p.stages||[]).map((s:any)=>s.name).join(" → ")}</p></div>)}</div></section>
 <section className="rounded-2xl border border-[#DDE5EA] bg-white p-6"><div className="flex items-start justify-between"><div><h2 className="text-base font-semibold text-[#173454]">Assessments</h2><p className="mt-1 text-xs text-[#71859A]">Reusable tests, work samples and evaluations.</p></div><Link href="/employer/assessments/new" className="rounded-xl border border-[#B9DDD7] px-3 py-2 text-xs font-medium text-[#167D73]"><Plus size={14} className="inline mr-1"/>Create</Link></div><div className="mt-5 space-y-3">{assessments.length===0?<div className="rounded-xl bg-[#F5F8F8] p-4 text-xs leading-5 text-[#71859A]">No assessments yet. Create one only when a role needs a structured evaluation.</div>:assessments.map(a=><div key={a.id} className="rounded-xl border border-[#EEF2F4] p-4"><p className="text-sm font-medium text-[#173454]">{a.name}</p><p className="mt-1 text-xs text-[#71859A]">{a.type} · {a.status}</p></div>)}</div></section></div>
 {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-[#173454]/20 p-4"><div className="w-full max-w-2xl rounded-2xl bg-white p-6 shadow-[0_20px_60px_rgba(23,52,84,0.18)]"><h2 className="text-lg font-semibold text-[#173454]">Create a hiring pipeline</h2><p className="mt-1 text-xs text-[#71859A]">Use clear stage names. You can change the sequence later.</p><input className="input mt-4" value={name} onChange={e=>setName(e.target.value)} placeholder="Senior technology hiring"/><div className="mt-4 space-y-2">{stages.map((s,i)=><div key={i} className="flex gap-2"><input className="input flex-1" value={s.name} onChange={e=>setStages(v=>v.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><select className="input w-44" value={s.type} onChange={e=>setStages(v=>v.map((x,j)=>j===i?{...x,type:e.target.value}:x))}><option>Screening</option><option>Assessment</option><option>Interview</option><option>Hiring Manager Review</option><option>Approval</option><option>Offer</option><option>Hired</option><option>Custom</option></select><button onClick={()=>setStages(v=>v.filter((_,j)=>j!==i))} className="px-2 text-[#9AA8B3]"><Trash2 size={15}/></button></div>)}</div><button onClick={()=>setStages(v=>[...v,{name:"New stage",type:"Custom"}])} className="mt-3 text-xs font-medium text-[#167D73]">+ Add stage</button><div className="mt-6 flex justify-end gap-2"><button onClick={()=>setOpen(false)} className="rounded-xl px-4 py-2.5 text-sm text-[#71859A]">Cancel</button><button disabled={saving} onClick={save} className="rounded-xl bg-[#167D73] px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">{saving?"Saving…":"Save pipeline"}</button></div></div></div>}
 </div></div></EmployerShell>
}